### ISSUE TITLE
missing blog template for learn2

### ISSUE THREAD

**Issue by rantwolf** [getgrav/grav-theme-learn2#95]
is it possible to add a blog style template for this theme?

**Comment by rhukster** [comment]
It's not missing because this theme is intended as a documentation theme.  You can however try porting the blog twig templates from another theme into this theme if you need a blog in the same theme as your documentation. However, this will undoubtedly require some additional css and styling to fit in.  This is way beyond the intended purpose of this theme however, and that comes under the definition of "custom styling".
